name: linter

on:
  push:
    branches: [main]
    paths:
      - '**/*.go'

  pull_request:
    branches: [main]
    paths:
      - '**/*.go'

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with: 
          go-version: '^1.23.0'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.0